"use client";
import Header from "../components/Header/Header";

import { AuthContext } from "../contexts/AuthContext";

import "./globals.css";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isUserLoggedIn, setIsUserLoggedIn] = useState(false);

  useEffect(() => {
    const token = localStorage.getItem("token");

    if (token) {
      setIsUserLoggedIn(true);
    }
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext.Provider
          value={{
            isUserLoggedIn: isUserLoggedIn,
            name: "John Doe",
            setIsUserLoggedIn: setIsUserLoggedIn,
          }}
        >
          <Header />
          {children}
        </AuthContext.Provider>
      </body>
    </html>
  );
}

// RSC - React server component
